const response = require('../utlis/responseHandler')
const otpGenerate = require('../utlis/otpGenerator')
const sendOtpToGmail = require('../service/emailService')
const User = require('../models/User')
const generateToken = require('../utlis/generateToken')
const twilloService = require('../service/twilloService')
const Conversation = require('../models/Conversation')
const { uploadFileToCloudinary, deleteFromCloudinary } = require('../config/cloudinary')

// Send OTP
const sendOtp = async (req, res) => {
  const { phoneNumber, phoneSuffix, email } = req.body
  const otpExpiry = new Date(Date.now() + 5 * 60 * 1000)

  try {
    let user
    if (email) {
      const lowerEmail = email.toLowerCase();
      user = await User.findOne({ email: lowerEmail })
      if (!user) user = new User({ email: lowerEmail })
      const otp = otpGenerate() // OTP for email is still generated by your app
      user.emailOtp = otp
      user.emailOtpExpiry = otpExpiry
      await user.save()
      await sendOtpToGmail(email, otp)
      return response(res, 200, 'Otp sent successfully to email')
    }

    if (!phoneNumber || !phoneSuffix) {
      return response(res, 400, 'Phone number is required')
    }

    const fullPhoneNumber = `+${phoneSuffix}${phoneNumber}`
    user = await User.findOne({ phoneNumber, phoneSuffix })
    if (!user) user = new User({ phoneNumber, phoneSuffix })
    await user.save()

    await twilloService.sendOTP(fullPhoneNumber)

    return response(res, 200, 'Otp sent successfully to your phone')
  } catch (e) {
    console.error(e)
    return response(res, 500, e.message || 'Failed to send otp')
  }
}

// OTP Verification
const otpVerification = async (req, res) => {
  const { phoneNumber, phoneSuffix, email, otp } = req.body

  try {
    let user
    if (email) {
      const lowerEmail = email.toLowerCase();
      user = await User.findOne({ email: lowerEmail })
      if (!user) return response(res, 404, 'User not found')

      const now = new Date()
      if (!user.emailOtp || String(user.emailOtp) !== String(otp) || now > new Date(user.emailOtpExpiry)) {
        return response(res, 400, 'Invalid or expired otp')
      }
      user.emailOtp = null
      user.emailOtpExpiry = null
    } else {
      if (!phoneNumber || !phoneSuffix) return response(res, 400, 'Phone number is required')
      const fullPhoneNumber = `+${phoneSuffix}${phoneNumber}` // Define fullPhoneNumber here
      user = await User.findOne({ phoneNumber, phoneSuffix })
      if (!user) return response(res, 404, 'User not found')

      try {
        const result = await twilloService.verifyOTP(fullPhoneNumber, otp)
        if (!result || result.status !== 'approved') {
          return response(res, 400, 'Invalid or expired otp')
        }
      } catch (err) {
        if (err.status === 404) {
          return response(res, 400, 'OTP expired or not requested. Please resend.')
        }
        throw err;
      }
    }

    user.isVerified = true
    await user.save()

    const token = generateToken(user._id)
    res.cookie('auth_token', token, {
      httpOnly: true,
      maxAge: 30 * 24 * 60 * 60 * 1000,
      sameSite: "none",
      secure: true
    })

    return response(res, 200, 'Otp verified successfully', { user })
  } catch (e) {
    console.error(e)
    return response(res, 500, e.message || 'Failed to verify otp')
  }
}

// Update Profile
const updateProfile = async (req, res) => {
    const {username, agreed, about} = req.body
    const userId = req.user.userId
    try{
        const user = await User.findById(userId)
        const file = req.file
        if(file) {
            if (process.env.CLOUDINARY_API_KEY) {
                const uploadResult = await uploadFileToCloudinary(file)
                console.log("✅ Image uploaded to Cloudinary successfully!")
                console.log("🔗 Image URL:", uploadResult?.secure_url)
                user.profilePicture = uploadResult?.secure_url
            } else {
                console.warn("Cloudinary keys missing in .env. Skipping profile picture upload.");
            }
        }
        else if(req.body.profilePicture) user.profilePicture = req.body.profilePicture
        if(username) user.username = username
        if(agreed) user.agreed = agreed
        if(about) user.about = about
        user.isProfileCompleted = true
        await user.save()
        return response(res,200,'Profile updated successfully', { user })
    }
    catch(e){
        console.error(e)
        return response(res,500, e.message || 'Failed to update profile')
    }

}

// check Authenticate
const checkAuthenticate = async (req, res) => {
    try{
        const userId = req.user.userId
        if(!userId) return response(res,404, 'Unauthorized user')
        const user = await User.findById(userId)
        if(!user) return response(res,404, 'Unauthorized user')
        return response(res, 200, "User retrived successfully", { user })  
    }
    catch(e){
        console.error(e)
    }
    return;

}

// Log Out 
const logout = async (req, res) => {
    try{
        res.cookie('auth_token', '', {
            httpOnly: true,
            expires: new Date(0),
            sameSite: "none",
            secure: true
        })
        console.log('LogOut Successfully !')
        return response(res,200,'LogOut Successfully !')
    }
    catch(e){
        console.error(e)
        return response(res,500,'Failed to logout')
    }
}

// get all user
const getAllUser = async (req, res) => {
    const loggedInUserId = req.user.userId
    try{
        const users = await User.find({ _id: { $ne: loggedInUserId } }).select(
            "username profilePicture about isOnline lastSeen phoneNumber phoneSuffix email"
        ).lean()
        const userWithConversation = await Promise.all(
            users.map(async(user) => {
                const conversation = await Conversation.findOne({
                    participants: { $all: [loggedInUserId, user?._id] }
                }).populate({
                    path: "lastMessage",
                    select: "content createdAt sender receiver"
                }).lean()
                return {
                    ...user,
                    conversation: conversation ? conversation : null
                }
            })
        )
        return response(res, 200, "Users retrieved successfully", userWithConversation)
    }
    catch(e){
        console.error(e)
        return response(res, 500, "Failed to retrieve users")
    }
}


module.exports = { sendOtp, otpVerification, updateProfile, logout, checkAuthenticate, getAllUser }
